### ISSUE TITLE
About sliding_window_inference of monai

### ISSUE THREAD

**Issue by uto-lt** [a-parida12/dcm-anon#7]
Hi, a-parida12
I saw the question you issued in a discussion, which is how to use the sliding_window_inference of monai for a case with multiple inputs and single outputs. I have the same need now, and I wonder if you have solved the problem.
I don't know how to contact you, so I take the liberty to ask this question under this repository.
Thank you.

**Comment by a-parida12** [comment]
@uto-lt . I did do a hack around to be able to the `sliding_window_inference` for using it in multiple inputs and single output scenarios. Please tag me in the discussion on MOnai using my user @ a-parida12. I will put my sample code there.

I am closing this issue as irrelevant.
